### ISSUE TITLE
Data scope

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-canadian-biodiversity#1]
Hi @cgendreau 
I've added an initial attempt at a data scope. Canada only.
https://github.com/gbif/hp-canadian-biodiversity/commit/116a858f3e642e5aae2528d2bd821c2437ca2ab6

But in the project description it is mentioned that perhaps areas across the borders should be included as well. If that is the case, then we should find a different approach.

**Comment by cgendreau** [comment]
thanks @MortenHofft !

cc @jocelynpender

**Comment by jocelynpender** [comment]
@MortenHofft We've decided to work with Canada scope only, for now. So your code is appropriate. Thanks!
I'll reopen this issue if we decide otherwise.

**Comment by MortenHofft** [comment]
Feel free to do so. If you feel adventerous then this is where to change it
https://github.com/gbif/hp-canadian-biodiversity/blob/master/_includes/js/config.js#L6

and the format is documented here
https://www.gbif.org/developer/occurrence#predicates

That said there are still minor discrepancies between the API v1 documentation and the graphql usage.
