### ISSUE TITLE
Title of the site on the French side is "CBIF"

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#13]
**Describe the bug**
When on the French version of the site, in the header bar, the site title is "CBIF".
![image](https://user-images.githubusercontent.com/16246446/116898525-78b66c80-ac04-11eb-9139-4b234b377fe7.png)

**Expected behavior**
The title should be SCIB on the French site, which is the French translation for CBIF.

**Comment by MortenHofft** [comment]
The title is the same for the whole site. Could you create a feature request on the hosted portals repo for this please?

**Comment by mbelisle** [comment]
We have landed on BioMob as the title in both French and English.
