### ISSUE TITLE
Help extracting occurrence IDs on the Data page

### ISSUE THREAD

**Issue by mbelisle** [gbif/hp-canadian-biodiversity#16]
@MortenHofft 
I have been experimenting with the Data page in order to make accessible the occurrence IDs associated with the current filters without having the download the results.  I have added two buttons - one to copy the IDs to the clipboard, the other to include them in an email.  This would be for the eventual ability to seamlessly send specimen requests to our in-house collections.

My current strategy is to translate the filter in the URL to an API request and obtain the results that way.  I worry about using this strategy because:
- Some of the filters don't have an exact equivalent in the occurrence API (e.g. "notIssue")
- Translating each possible type of filter to an API equivalent seems like a duplication of work and is likely error prone

Would you have a suggestion for a better strategy? I'm thinking that making a graphql request might make more sense.

Contents of _includes/js/script.js:
```
 function getFilter() {
    let searchParams = new URLSearchParams(window.location.search);
    let encodedFilter = searchParams.get("filter");
    if (!encodedFilter) filter = {};
    else filter = JSON.parse(atob(encodedFilter)).must;
    filter["country"] = 'CA';
    // filter does not include the equivalent of the key-value pair "notIssues": "COUNTRY_COORDINATE_MISMATCH"
    // contained in the root predicate.
    return filter;
 }

 function hasAAFCSingleCollectionFilter() {
    return (filter.hasOwnProperty('collectionCode') &&
        (filter.collectionCode.length == 1) &&
        (['AGRC', 'CNC', 'DAO', 'DAOMC', 'DAOM', 'PGRC'].includes(filter.collectionCode[0].toUpperCase())));
 }

 function updateGetIdButtons() {
    let requestButton = document.getElementById("requestIds");
    filter = getFilter();
    if (filter && hasAAFCSingleCollectionFilter()) {
      requestButton.disabled = false;
    } else {
      requestButton.disabled = true;
    }
 }


async function getIds(buttonID) {
  console.log(filter)
  // still buggy with year range
  if (filter && filter.hasOwnProperty('year')) {
    filter.year = await(convertFilterYears());
  }
  let jqueryString = $.param(filter, true);
  console.log(jqueryString)
  let apiString = 'https://api.gbif.org/v1/occurrence/search?' + jqueryString + '&limit=100';
  console.log(apiString);
  let response = await fetch(apiString);
  let data = await response.json();
  const ids = await data.results.map(d => d.key);
  if (buttonID == "requestIds") {
    let recipient = getCollectionEmail(filter.collectionCode[0]);
    createMailerMessage(recipient, ids.toString());
  } else {
    //this part not working with alert. Need to fix document focus issue
    navigator.clipboard.writeText(ids);
    //alert("ID list copied to clipboard.");
  }
 }

async function convertFilterYears() {
  var years = [];
  filter.year.forEach(e => {
    if (e.type === 'equals') years.push(e.value);
    if (e.type === 'range') {
      let end = e.value.lte;
      let start = parseInt(e.value.gte);
      let individualYears = Array(end - start + 1).fill().map((_, idx) => start + idx);
      years.push(individualYears);
    }
  });
  return years.flat();
 }

function createMailerMessage(recipient, idList) {
    let body = "Request specimen information for the following specimen IDs: " + encodeURIComponent(idList);
    let link =
        "mailto:" +
        recipient +
        "&subject=" +
        encodeURIComponent("Information Request from Hosted-Portal!") +
        "&body=" +
        body;
    window.location.href = link;
}

function getCollectionEmail(collectionCode) {
    //TODO: get email address from collectionCode
    return "cnc@example.com";
}
```

![image](https://user-images.githubusercontent.com/43251641/142011714-cbc5246c-0160-49fa-91cf-de97cc435cf4.png)

**Comment by MortenHofft** [comment]
First of all I'm impressed that you managed to do this, it isn't exactly documented how those urls work.

This makes perfect sense, but I do not know what the best solution is. But I - like you - feel that above isn't ideal. Perhaps it would be useful to [create an issue in the hosted portal repository](https://github.com/gbif/hosted-portals/issues/new) so that others are more likely to see and comment? I'm curious to know if others are interested in this. I will help find a solution either way, but the solution could depend on how much interest there is in this.

**Comment by mbelisle** [comment]
Thanks Morten.  I have created a [new issue](https://github.com/gbif/hosted-portals/issues/197) as you suggested and will close this one.
