### ISSUE TITLE
Language landing page

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-canadian-biodiversity#2]
Hi @jocelynpender
I have noticed that https://www.cbif.gc.ca/ has a language landing page instead of showing one language as the default. That is possible on this site as well. Something a la https://hp-base-theme.gbif-staging.org/language

It isn't documented yet https://github.com/gbif/hosted-portals/issues/34, but I can set it up for you.

**Comment by jocelynpender** [comment]
Yes, this is what we'd like! This is the strategy used by all gov pages, so I'm 99% certain we'd like to conform to this. @jmacklin chime in if you think otherwise.

**Comment by MortenHofft** [comment]
I have now changed the site setup to have a language selection page as the landing page. 
https://github.com/gbif/hp-canadian-biodiversity/commit/959dce3a9d2282d08eca6f0b6456b546ec2e6fcc

**Comment by jocelynpender** [comment]
Looks great!
