### ISSUE TITLE
The translation button only appears on some pages

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#6]
**Describe the bug**
The translation widget to toggle between languages does not appear on every page. It appears on the Home page, the Data page, News page and not on the About page, Tools page and GRDI page.

**Expected behavior**
If this widget is going to be useful, I expect it to appear on every page.

**Screenshots**
From **Data** page:
![image](https://user-images.githubusercontent.com/16246446/109977576-f3c5da00-7cca-11eb-861c-ce398bb985f6.png)
From **About** page:
![image](https://user-images.githubusercontent.com/16246446/109977614-fb857e80-7cca-11eb-9036-421cfb9b2d9b.png)

**Desktop:**

- MacOS High Sierra 10.13.6
- Chrome Version 88.0.4324.182 (Official Build) (x86_64)

TODO: Test with different browsers and devices.

**Comment by MortenHofft** [comment]
Hi @jocelynpender 
This isn't properly documented (see also https://github.com/gbif/hosted-portals/issues/29) so you have no way of knowing - but the short answer is that your pages do not have the correct front matter.

Translations are linked by the `lang-ref` attribute.

If you compare the data pages that show correctly
[english data page](https://github.com/gbif/hp-canadian-biodiversity/blob/136cf2947bfab4916c9bdf2eaba532cea50362b7/data.md) and [french data page](https://github.com/gbif/hp-canadian-biodiversity/blob/5a9093a1c6ac5eb640d8487bf97499330627b19f/fr/data.md) you see they both have `lang-ref: data` in their front matter.

Whereas the about pages do not
[english](https://github.com/gbif/hp-canadian-biodiversity/blob/f4d4520fbd159c31a1615a8d3c52e89955e0db75/about.md) has `lang-ref: about` and [french](https://github.com/gbif/hp-canadian-biodiversity/blob/f4d4520fbd159c31a1615a8d3c52e89955e0db75/fr/apropos.md) has `lang-ref: apropos`

**Comment by MortenHofft** [comment]
I've commited a fix to your frontmatter so that the about pages gets linked

**Comment by jocelynpender** [comment]
@MortenHofft  Thank you for the guidance. I've fixed the issue on the grdi and tools pages.
