### ISSUE TITLE
"Powered by GBIF" appears in English on the French site

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#7]
**Describe the bug**
There doesn't seem to be a way for me to translate the sentence "Powered by GBIF" for the French side of the site.

**Expected behavior**
I expect to be able to display "Propulsé par GBIF" or something similar.

**Screenshots**
Here is the footer on the French site:
![image](https://user-images.githubusercontent.com/16246446/109978138-8f574a80-7ccb-11eb-9aff-c2b6f19a1c93.png)

**Comment by kcopas** [comment]
The text is a placeholder for a logo that will be displayed across all hosted portals, which will link back to GBIF. 

As mentioned in https://github.com/gbif/hosted-portals/issues/97:

> the point of the "powered by" branding…is that it will consistently identify the hosted portals as served by the GBIF infrastructure.

**Comment by jmacklin** [comment]
So, the expectation here is to leave the logo button as is in English on the French pages? I think we can get away with that if it is a logo... But, it should not be much effort to make a French (and other languages) logo image and maintain the link, right, or is this embedded in the template?

**Comment by kcopas** [comment]
I'm still developing the concept @jmacklin but the intention is that it's simple enough to avoid translation. _Avec mes excuses_, while it would be simple enough for French, the precedent would set us down a slippery slope for Russian, Chinese and other non-Roman character sets.
